version: "3.9"
services:
  movie:
    build: ./movie/
    ports:
      - "3000:3000"
  showtime:
    build: ./showtime/
    ports:
      - "3002:3002"
  user:
    build: ./user/
    ports:
      - "3003:3003"
  booking:
    build: ./booking/
    ports:
      - "3001:3001"
