# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"#\n\tAllMovies\x12\x16\n\x06movies\x18\x01 \x03(\x0b\x32\x06.Movie\"2\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"0\n\x08Schedule\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x16\n\x06movies\x18\x02 \x03(\x0b\x32\x06.Movie\"A\n\x0e\x42ookingRequest\x12\x0f\n\x07movieid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\" \n\x06Status\x12\x16\n\x0e\x62ooking_status\x18\x01 \x01(\t\"\x15\n\x07UserIdB\x12\n\n\x02id\x18\x01 \x01(\t\":\n\rBookingsUserB\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x19\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\n.DateItemB\")\n\tDateItemB\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x07\n\x05\x45mpty2\xb2\x01\n\x04User\x12*\n\x12GetMoviesPerRating\x12\x06.Empty\x1a\n.AllMovies\"\x00\x12$\n\x0eGetMovieAtDate\x12\x05.Date\x1a\t.Schedule\"\x00\x12\'\n\tBookMovie\x12\x0f.BookingRequest\x1a\x07.Status\"\x00\x12/\n\x11GetBookingForUser\x12\x08.UserIdB\x1a\x0e.BookingsUserB\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLMOVIES']._serialized_start=14
  _globals['_ALLMOVIES']._serialized_end=49
  _globals['_MOVIE']._serialized_start=51
  _globals['_MOVIE']._serialized_end=101
  _globals['_DATE']._serialized_start=103
  _globals['_DATE']._serialized_end=123
  _globals['_SCHEDULE']._serialized_start=125
  _globals['_SCHEDULE']._serialized_end=173
  _globals['_BOOKINGREQUEST']._serialized_start=175
  _globals['_BOOKINGREQUEST']._serialized_end=240
  _globals['_STATUS']._serialized_start=242
  _globals['_STATUS']._serialized_end=274
  _globals['_USERIDB']._serialized_start=276
  _globals['_USERIDB']._serialized_end=297
  _globals['_BOOKINGSUSERB']._serialized_start=299
  _globals['_BOOKINGSUSERB']._serialized_end=357
  _globals['_DATEITEMB']._serialized_start=359
  _globals['_DATEITEMB']._serialized_end=400
  _globals['_EMPTY']._serialized_start=402
  _globals['_EMPTY']._serialized_end=409
  _globals['_USER']._serialized_start=412
  _globals['_USER']._serialized_end=590
# @@protoc_insertion_point(module_scope)
